### PR TITLE
Update train.py to support subsampling the dataset

### PR DESCRIPTION
**Pull request by JinfengX**
Add parameters 'train_subsampling_ratio' and 'eval_subsampling_ratio' to obtain a subset of dataset

### CODE REVIEW

**Comment by Gofinge** [comment]
Hi, Jingfeng. Could you give me a brief explanation of the meaning of introducing this function?

**Comment by JinfengX** [comment]
Sure! This function allows users to obtain a subset of a dataset. Using a subset of a dataset in machine learning reduces computation time, enables efficient prototyping, and helps identify data issues early. This approach streamlines model development and debugging before scaling up to the full dataset. For a detailed explanation, refer to this article: [link](https://medium.com/@siddharth.tumre/how-to-create-a-subset-of-dataloader-in-pytorch-and-why-is-it-important-52c238a7199). Thanks!

**Comment by JinfengX** [comment]
> Hi, Jingfeng. Could you give me a brief explanation of the meaning of introducing this function?

Sure! This function allows users to obtain a subset of a dataset. Using a subset of a dataset in machine learning reduces computation time, enables efficient prototyping, and helps identify data issues early. This approach streamlines model development and debugging before scaling up to the full dataset. For a detailed explanation, refer to this article: [link](https://medium.com/@siddharth.tumre/how-to-create-a-subset-of-dataloader-in-pytorch-and-why-is-it-important-52c238a7199). Thanks!

**Comment by JinfengX** [comment]
Thanks for your suggestions! I will submit another pull request for enhancing this function.

**Comment by Gofinge** [comment]
Welcome, and thank you for being one of Pointcept's contributors.

**Pull request closed without merging**
